llm:
  api_type: "azure"  # or azure / ollama / groq etc.
  model: "gpt-4.1"  # or gpt-3.5-turbo
  base_url: "https://midas-openai2.openai.azure.com/openai/deployments/gpt-4.1/"  # or forward url / other llm url
  api_key: ""

models:
 "gpt-4.1": # model: "gpt-4.1"  # or gpt-3.5-turbo
   api_type: "azure"  # or azure / ollama / groq etc.
   base_url: "https://midas-openai2.openai.azure.com/openai/deployments/gpt-4.1/"  # or forward url / other llm url
   api_key: ""
   temperature: 0